import datetime as _dt
import hashlib
import json
import os
import re
import shlex
import shutil
import subprocess
import sys
import tempfile
from collections import deque
from io import BytesIO
from pathlib import Path

from PyQt6.QtCore import Qt, QThread, pyqtSignal
from PyQt6.QtGui import QDragEnterEvent, QDropEvent, QIcon, QPixmap, QTextCursor
from PyQt6.QtWidgets import (
    QApplication,
    QCheckBox,
    QDoubleSpinBox,
    QFileDialog,
    QFormLayout,
    QGridLayout,
    QGroupBox,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QMainWindow,
    QMessageBox,
    QPushButton,
    QPlainTextEdit,
    QSpinBox,
    QTabWidget,
    QVBoxLayout,
    QWidget,
)


APP_NAME = "EXE Toolbox"
APP_VERSION = "1.9.0"
APP_ICON_FILE = "ExeCreator_Icon.ico"
BUILD_STAMP_FILENAME = "EXE_TOOLBOX_BUILD.json"

# V1.8: libs that, when present in the build interpreter without being declared
# in requirements.txt, inflate the EXE far beyond what the app needs. Used to
# warn the user about fat-venv builds. (Inspired by a real 115 MB StoryTeller
# build that dragged in pandas/scipy/etc. via transitive optional imports.)
HEAVY_LIBS = {
    "numpy", "pandas", "scipy", "sympy", "matplotlib", "seaborn",
    "torch", "tensorflow", "jax", "transformers", "sklearn",
    "scikit-learn", "scikit_learn",
    "lxml", "openpyxl", "xlrd", "xlsxwriter",
    "sqlalchemy", "alembic",
    "pygments", "fsspec", "boto3", "botocore",
    "pyarrow", "polars", "duckdb",
    "paddleocr", "paddlepaddle", "paddlex",
}

# V1.8: parent dirs whose presence in target_py's path means the user probably
# selected a snapshot/old copy instead of the live source.
SNAPSHOT_DIR_NAMES = {
    "versioncontrol", "version_control", "version-control",
    "oldmains", "old_mains", "old-mains",
    "archive", "archives", "snapshots", "snapshot",
    "backup", "backups", "old", "_old",
}

# -----------------------------
# Portable app-folder helpers
# -----------------------------
def get_app_dir() -> Path:
    """
    When running as .py: returns the folder containing this .py file.
    When frozen as .exe: returns the folder containing the .exe.
    """
    if getattr(sys, "frozen", False):
        return Path(sys.executable).resolve().parent
    return Path(__file__).resolve().parent

def get_resource_path(filename: str) -> Path:
    meipass = getattr(sys, "_MEIPASS", None)
    if meipass:
        return Path(meipass) / filename
    return get_app_dir() / filename


def apply_app_icon(app_or_window) -> None:
    icon_path = get_resource_path(APP_ICON_FILE)
    if icon_path.exists():
        app_or_window.setWindowIcon(QIcon(str(icon_path)))


def make_safe_app_id_part(value: str) -> str:
    """
    Windows AppUserModelID accepts a dotted identifier. Keep it boring and stable:
    letters, numbers, dots, underscores, and hyphens only.
    """
    cleaned = re.sub(r"[^A-Za-z0-9._-]+", ".", str(value).strip())
    cleaned = re.sub(r"\.{2,}", ".", cleaned).strip(".")
    return cleaned or "App"


def default_app_user_model_id(exe_name: str) -> str:
    return f"Can.{make_safe_app_id_part(exe_name)}"


def set_windows_app_id(app_id: str) -> None:
    """
    Set this process' Windows taskbar identity. This helps PyQt windows use the
    real app icon instead of falling back to a generic/blank icon when unpinned.
    """
    if not sys.platform.startswith("win"):
        return
    try:
        import ctypes
        ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelID(str(app_id))
    except Exception:
        pass


def write_appid_runtime_hook(path: Path, app_id: str) -> Path:
    """
    Create a tiny PyInstaller runtime hook. PyInstaller runs hooks before the
    target app starts, so the AppUserModelID is set before QApplication exists.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    hook_code = (
        "\"\"\"\n"
        f"Runtime hook generated by EXE Toolbox V{APP_VERSION}.\n"
        "Sets Windows AppUserModelID early so PyQt taskbar icons behave correctly.\n"
        "\"\"\"\n"
        "import sys\n\n"
        "if sys.platform.startswith(\"win\"):\n"
        "    try:\n"
        "        import ctypes\n"
        f"        ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelID({app_id!r})\n"
        "    except Exception:\n"
        "        pass\n"
    )
    path.write_text(hook_code, encoding="utf-8")
    return path


def write_pyqt_icon_runtime_hook(path: Path, icon_filename: str) -> Path:
    """
    Create a PyInstaller runtime hook that force-applies the bundled icon to
    QApplication and top-level PyQt6 widgets. This is for the Windows taskbar
    case where --icon is embedded correctly but the live PyQt window still uses
    a blank/default icon unless pinned.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    hook_code = (
        "\"\"\"\n"
        f"Runtime hook generated by EXE Toolbox V{APP_VERSION}.\n"
        "Force-applies the bundled icon to PyQt6 QApplication/windows.\n"
        "\"\"\"\n"
        "import os\n"
        "import sys\n\n"
        f"_EXE_TOOLBOX_ICON_FILENAME = {icon_filename!r}\n\n"
        "def _find_icon_path():\n"
        "    candidates = []\n"
        "    meipass = getattr(sys, '_MEIPASS', None)\n"
        "    if meipass:\n"
        "        candidates.append(os.path.join(meipass, _EXE_TOOLBOX_ICON_FILENAME))\n"
        "    try:\n"
        "        candidates.append(os.path.join(os.path.dirname(sys.executable), _EXE_TOOLBOX_ICON_FILENAME))\n"
        "    except Exception:\n"
        "        pass\n"
        "    try:\n"
        "        candidates.append(os.path.join(os.getcwd(), _EXE_TOOLBOX_ICON_FILENAME))\n"
        "    except Exception:\n"
        "        pass\n"
        "    for p in candidates:\n"
        "        if p and os.path.exists(p):\n"
        "            return p\n"
        "    return None\n\n"
        "def _make_icon():\n"
        "    p = _find_icon_path()\n"
        "    if not p:\n"
        "        return None\n"
        "    try:\n"
        "        from PyQt6.QtGui import QIcon\n"
        "        icon = QIcon(p)\n"
        "        if not icon.isNull():\n"
        "            return icon\n"
        "    except Exception:\n"
        "        return None\n"
        "    return None\n\n"
        "def _apply_icon_to_app_and_windows():\n"
        "    try:\n"
        "        from PyQt6.QtWidgets import QApplication\n"
        "        app = QApplication.instance()\n"
        "        if app is None:\n"
        "            return\n"
        "        icon = _make_icon()\n"
        "        if icon is None:\n"
        "            return\n"
        "        app.setWindowIcon(icon)\n"
        "        for w in app.topLevelWidgets():\n"
        "            try:\n"
        "                w.setWindowIcon(icon)\n"
        "            except Exception:\n"
        "                pass\n"
        "    except Exception:\n"
        "        pass\n\n"
        "def _install_pyqt6_icon_patch():\n"
        "    try:\n"
        "        from PyQt6.QtWidgets import QApplication, QWidget\n"
        "    except Exception:\n"
        "        return\n\n"
        "    if getattr(QApplication, '_exe_toolbox_icon_patch_installed', False):\n"
        "        return\n"
        "    QApplication._exe_toolbox_icon_patch_installed = True\n\n"
        "    original_qapp_init = QApplication.__init__\n"
        "    def patched_qapp_init(self, *args, **kwargs):\n"
        "        original_qapp_init(self, *args, **kwargs)\n"
        "        _apply_icon_to_app_and_windows()\n"
        "    QApplication.__init__ = patched_qapp_init\n\n"
        "    original_show = QWidget.show\n"
        "    def patched_show(self, *args, **kwargs):\n"
        "        try:\n"
        "            app = QApplication.instance()\n"
        "            icon = None\n"
        "            if app is not None:\n"
        "                icon = app.windowIcon()\n"
        "            if icon is None or icon.isNull():\n"
        "                icon = _make_icon()\n"
        "                if app is not None and icon is not None:\n"
        "                    app.setWindowIcon(icon)\n"
        "            if icon is not None and not icon.isNull():\n"
        "                self.setWindowIcon(icon)\n"
        "        except Exception:\n"
        "            pass\n"
        "        return original_show(self, *args, **kwargs)\n"
        "    QWidget.show = patched_show\n\n"
        "    try:\n"
        "        from PyQt6.QtCore import QTimer\n"
        "        original_exec = QApplication.exec\n"
        "        def patched_exec(self, *args, **kwargs):\n"
        "            try:\n"
        "                QTimer.singleShot(0, _apply_icon_to_app_and_windows)\n"
        "                QTimer.singleShot(500, _apply_icon_to_app_and_windows)\n"
        "            except Exception:\n"
        "                pass\n"
        "            # In PyQt6, QApplication.exec is exposed like a static callable.\n"
        "            # If we call original_exec(self), frozen apps can crash with:\n"
        "            # TypeError: exec() too many arguments. Try the safe forms.\n"
        "            last_exc = None\n"
        "            for call_args in ((self,) + tuple(args), tuple(args), ()): \n"
        "                try:\n"
        "                    return original_exec(*call_args, **kwargs)\n"
        "                except TypeError as exc:\n"
        "                    last_exc = exc\n"
        "                    continue\n"
        "            if last_exc is not None:\n"
        "                raise last_exc\n"
        "            return original_exec()\n"
        "        QApplication.exec = patched_exec\n"
        "    except Exception:\n"
        "        pass\n\n"
        "_install_pyqt6_icon_patch()\n"
    )
    path.write_text(hook_code, encoding="utf-8")
    return path

def default_python_command() -> str:
    """
    When this tool runs as .py, sys.executable is the correct Python.

    When this tool runs as .exe, sys.executable is the toolbox EXE itself,
    not a Python interpreter. In that case, prefer the Python launcher:
        py -3
    and fall back to python if needed.

    Important:
    Return py -3, not "C:\\Windows\\py.EXE" -3.
    Quoted py.EXE paths caused WinError 2 / command parsing issues.
    """
    if not getattr(sys, "frozen", False):
        return str(Path(sys.executable).resolve())

    if shutil.which("py"):
        return "py -3"

    if shutil.which("python"):
        return "python"

    # Last-resort hint, neither `py` nor `python` resolved on PATH. Return a
    # bare default so the GUI field is editable; the user fixes it manually.
    return "python"


def split_command(command_text: str) -> list[str]:
    """
    Robustly parse the Python command field.

    Supported examples:
      C:\\Python312\\python.exe
      "C:\\Python312\\python.exe"
      py -3
      "C:\\Windows\\py.EXE" -3

    Fix:
    shlex.split(..., posix=False) preserves quote characters on Windows.
    Passing ['"C:\\Windows\\py.EXE"', '-3'] to subprocess causes WinError 2.
    This function strips wrapping quotes from the executable and arguments.
    """
    text = command_text.strip()
    if not text:
        return []

    def strip_wrapping_quotes(value: str) -> str:
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in ("'", '"'):
            return value[1:-1]
        return value

    # Quoted executable path, optionally followed by args.
    if text[0] in ("'", '"'):
        quote = text[0]
        end = text.find(quote, 1)
        if end == -1:
            return [strip_wrapping_quotes(text)]

        exe = text[1:end]
        rest = text[end + 1:].strip()
        parts = [exe]
        if rest:
            parts.extend(strip_wrapping_quotes(p) for p in shlex.split(rest, posix=False))
        return [p for p in parts if p]

    parts = shlex.split(text, posix=False)
    return [strip_wrapping_quotes(p) for p in parts if p]


def split_extra_args(command_text: str) -> list[str]:
    """
    Parse optional extra PyInstaller arguments.

    Example:
      --collect-all paddleocr --collect-all paddle --collect-all paddlex

    Also supports quoted paths if needed.
    """
    text = command_text.strip()
    if not text:
        return []

    def strip_wrapping_quotes(value: str) -> str:
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in ("'", '"'):
            return value[1:-1]
        return value

    parts = shlex.split(text, posix=False)
    return [strip_wrapping_quotes(p) for p in parts if p]


def normalize_user_path(path_value) -> Path:
    r"""
    Clean path text coming from QLineEdit / drag-drop / manual paste.

    Handles:
    - surrounding quotes
    - accidental doubled backslashes in normal drive paths
      example: C:\\Apps\\File.ico -> C:\Apps\File.ico
    """
    text = str(path_value).strip()

    if len(text) >= 2 and text[0] == text[-1] and text[0] in ("'", '"'):
        text = text[1:-1].strip()

    if re.match(r"^[A-Za-z]:", text):
        drive = text[:2]
        rest = text[2:].replace("/", "\\")
        rest = re.sub(r"\\{2,}", r"\\", rest)
        text = drive + rest

    return Path(text)


def pyinstaller_add_data_arg(source: Path, dest: str = ".") -> str:
    """
    Build a PyInstaller --add-data argument.

    PyInstaller uses:
      Windows: source;dest
      macOS/Linux: source:dest

    os.pathsep matches that rule:
      Windows ';'
      POSIX   ':'

    This lets a selected .ico be bundled inside a one-file EXE so PyQt apps can
    load it at runtime through sys._MEIPASS.
    """
    return f"{source}{os.pathsep}{dest}"


def open_folder(folder: Path) -> None:
    """
    Open a folder in the OS file manager.

    Used by the "Open output folder" buttons. Falls back gracefully so a bad
    path never crashes the GUI thread.
    """
    folder = Path(folder)
    try:
        if not folder.exists():
            folder = folder.parent
        if sys.platform.startswith("win"):
            os.startfile(str(folder))  # noqa: S606 - intended shell open
        elif sys.platform == "darwin":
            subprocess.Popen(["open", str(folder)])
        else:
            subprocess.Popen(["xdg-open", str(folder)])
    except Exception:
        pass


def resolve_data_entry(line: str, base_dir: Path) -> tuple[Path, str] | None:
    r"""
    Parse one "extra data file/folder" line into (resolved_source, dest_in_bundle).

    This is the fix for the classic packaged-Flask "Internal Server Error":
    PyInstaller only collects imported Python modules, so Jinja templates/,
    static/, icons and other non-import data must be declared explicitly.

    Accepted line forms (one entry per line):
        templates                 -> folder, dest = "templates"
        static                    -> folder, dest = "static"
        icon.png                  -> file,   dest = "."
        config\settings.ini       -> file,   dest = "."
        templates | templates     -> explicit SRC | DEST
        assets ; assets           -> PyInstaller-style ';' separator also accepted

    DEST defaults:
        - source is a directory -> DEST = the directory name (templates -> templates)
        - source is a file      -> DEST = "." (bundle root)

    A relative SRC is resolved against base_dir (the target .py's folder).
    A non-existent SRC raises FileNotFoundError: silently skipping is exactly
    what produced the original "missing templates -> HTTP 500" bug.
    """
    text = line.strip()
    if not text or text.startswith("#"):
        return None

    if "|" in text:
        src_text, dest = text.split("|", 1)
    elif ";" in text:
        src_text, dest = text.rsplit(";", 1)
    else:
        src_text, dest = text, ""

    src_text = src_text.strip()
    dest = dest.strip()

    src = normalize_user_path(src_text)
    if not src.is_absolute():
        src = (base_dir / src_text).resolve()

    if not src.exists():
        raise FileNotFoundError(
            f"Data file/folder not found: {src}\n"
            f"(from data entry: {text!r}). Fix the path or remove the line."
        )

    if not dest:
        dest = src.name if src.is_dir() else "."

    return src, dest


def split_hidden_imports(text: str) -> list[str]:
    """
    Parse the hidden-imports field. Accepts comma, whitespace, or newline
    separated module names, e.g. "pystray._win32, certifi  win32timezone".
    PyInstaller misses dynamically imported backends like pystray._win32.
    """
    text = (text or "").strip()
    if not text:
        return []
    parts = re.split(r"[\s,]+", text)
    return [p.strip() for p in parts if p.strip()]


# -----------------------------
# V1.8 helpers: provenance, fat-venv detection, stale-source detection
# -----------------------------
def sha256_file(path: Path, chunk: int = 1 << 20) -> str:
    """Stream-hash a file. Used to identify which source produced an EXE."""
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for block in iter(lambda: f.read(chunk), b""):
            h.update(block)
    return h.hexdigest()


def format_iso(ts: float) -> str:
    """POSIX timestamp -> local ISO 8601 with seconds precision and tz offset."""
    return _dt.datetime.fromtimestamp(ts).astimezone().isoformat(timespec="seconds")


def python_module_version(python_cmd: list[str], module: str) -> str | None:
    """
    Return the installed version string of `module` in the given Python, or
    None if it isn't importable / has no __version__.
    """
    try:
        result = subprocess.run(
            python_cmd + [
                "-c",
                f"import importlib, sys\n"
                f"try:\n"
                f"    m = importlib.import_module({module!r})\n"
                f"    sys.stdout.write(getattr(m, '__version__', '') or '')\n"
                f"except Exception:\n"
                f"    pass\n",
            ],
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            text=True,
            encoding="utf-8",
            errors="replace",
            check=False,
            **windows_no_console_kwargs(),
        )
        out = (result.stdout or "").strip()
        return out or None
    except Exception:
        return None


_REQ_NAME_RE = re.compile(r"^\s*([A-Za-z0-9][A-Za-z0-9._-]*)")


def parse_requirements_packages(req_path: Path) -> set[str]:
    """
    Extract top-level distribution names from a requirements.txt, normalized to
    lower-case with underscores->hyphens (PEP 503-ish), e.g.
    'scikit-learn==1.4 ; python_version>="3.10"' -> 'scikit-learn'.
    Ignores comments, blank lines, -r includes, editable installs.
    """
    names: set[str] = set()
    try:
        text = Path(req_path).read_text(encoding="utf-8", errors="replace")
    except Exception:
        return names

    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith(("#", "-r", "--", "-e ", "-c ")):
            continue
        m = _REQ_NAME_RE.match(line)
        if m:
            names.add(m.group(1).lower().replace("_", "-"))
    return names


def installed_distributions(python_cmd: list[str]) -> set[str]:
    """
    Lower-case, hyphen-normalized set of distribution names installed in the
    given Python. Used to detect 'heavy lib installed but not in reqs' bloat.
    """
    script = (
        "import importlib.metadata, sys\n"
        "for d in importlib.metadata.distributions():\n"
        "    n = d.metadata.get('Name')\n"
        "    if n: sys.stdout.write(n + '\\n')\n"
    )
    try:
        result = subprocess.run(
            python_cmd + ["-c", script],
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            text=True,
            encoding="utf-8",
            errors="replace",
            check=False,
            **windows_no_console_kwargs(),
        )
        return {
            line.strip().lower().replace("_", "-")
            for line in (result.stdout or "").splitlines()
            if line.strip()
        }
    except Exception:
        return set()


def heavy_libs_not_in_requirements(
    python_cmd: list[str], requirements_path: Path | None
) -> list[str]:
    """
    Return the sorted list of HEAVY_LIBS that are installed in the interpreter
    but NOT declared in requirements.txt. An empty list means the venv is lean
    relative to the declared deps.
    """
    installed = installed_distributions(python_cmd)
    declared = parse_requirements_packages(requirements_path) if requirements_path else set()
    heavy_norm = {h.lower().replace("_", "-") for h in HEAVY_LIBS}
    return sorted((heavy_norm & installed) - declared)


def target_imports_module(target_py: Path, module: str) -> bool:
    """
    Cheap textual check: does the target .py (or any .py beside it) contain a
    top-level `import {module}` or `from {module} ...`? Used so the
    'Detect web/Flask data' preset only wires pystray._win32 when pystray is
    actually used, instead of leaking it into every project.
    """
    if not module:
        return False
    pattern = re.compile(rf"^\s*(?:import|from)\s+{re.escape(module)}\b", re.MULTILINE)
    files: list[Path] = []
    target_py = Path(target_py)
    if target_py.is_file():
        files.append(target_py)
    base = target_py.parent if target_py.is_file() else target_py
    if base.is_dir():
        try:
            files.extend(p for p in base.glob("*.py") if p not in files)
        except Exception:
            pass
    for f in files:
        try:
            if pattern.search(f.read_text(encoding="utf-8", errors="ignore")):
                return True
        except Exception:
            pass
    return False


def stale_source_reason(target_py: Path) -> str | None:
    """
    Return a human-readable reason the chosen target_py looks stale, or None.

    Triggers:
      - target_py sits inside a snapshot/archive folder (Version_Control/, etc.)
      - a same-base-name `.py` in the same folder has a newer mtime
        (e.g. selected MyApp_V12.py while MyApp.py is newer next to it)
    """
    target_py = Path(target_py)
    for part in target_py.parts:
        if part.lower() in SNAPSHOT_DIR_NAMES:
            return (
                f"The selected file is inside a snapshot/archive folder ('{part}').\n"
                f"It is probably an OLD copy, not the live source.\n\n"
                f"Selection: {target_py}"
            )

    try:
        target_mtime = target_py.stat().st_mtime
    except Exception:
        return None

    base_stem = re.sub(r"[_-]?[vV]?\d+(?:[._-]\d+)*$", "", target_py.stem)
    if not base_stem:
        return None

    newest_sibling: Path | None = None
    newest_mtime = target_mtime
    try:
        for sib in target_py.parent.glob("*.py"):
            if sib == target_py:
                continue
            sib_stem = re.sub(r"[_-]?[vV]?\d+(?:[._-]\d+)*$", "", sib.stem)
            if sib_stem.lower() != base_stem.lower():
                continue
            try:
                m = sib.stat().st_mtime
            except Exception:
                continue
            if m > newest_mtime:
                newest_mtime = m
                newest_sibling = sib
    except Exception:
        return None

    if newest_sibling is not None:
        return (
            f"A newer same-base-name file exists in the same folder:\n"
            f"  newer: {newest_sibling}  ({format_iso(newest_mtime)})\n"
            f"  selected: {target_py}  ({format_iso(target_mtime)})\n\n"
            f"You may be building an old version."
        )
    return None


def write_build_stamp(
    stamp_path: Path,
    target_py: Path,
    exe_name: str,
    python_cmd: list[str],
    isolated_build: bool,
) -> dict:
    """
    Write EXE_TOOLBOX_BUILD.json next to the staged inputs and return the dict.
    Bundled via --add-data into the EXE root, so 'which source produced this
    EXE?' becomes a one-second sha256 check.
    """
    target_py = Path(target_py)
    st = target_py.stat()
    stamp = {
        "toolbox": APP_NAME,
        "toolbox_version": APP_VERSION,
        "built_at": format_iso(_dt.datetime.now().timestamp()),
        "exe_name": exe_name,
        "source_path": str(target_py.resolve()),
        "source_size_bytes": st.st_size,
        "source_mtime": format_iso(st.st_mtime),
        "source_sha256": sha256_file(target_py),
        "python_version": python_module_version(python_cmd, "sys") or "",
        "pyinstaller_version": python_module_version(python_cmd, "PyInstaller") or "",
        "isolated_build": bool(isolated_build),
        "host_platform": sys.platform,
    }
    # python_module_version of 'sys' returns '' (no __version__); replace with
    # a real reading via platform on the selected interpreter.
    try:
        result = subprocess.run(
            python_cmd + ["-c", "import sys; print(sys.version.split()[0])"],
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            text=True,
            encoding="utf-8",
            errors="replace",
            check=False,
            **windows_no_console_kwargs(),
        )
        stamp["python_version"] = (result.stdout or "").strip()
    except Exception:
        pass

    stamp_path = Path(stamp_path)
    stamp_path.parent.mkdir(parents=True, exist_ok=True)
    stamp_path.write_text(json.dumps(stamp, indent=2), encoding="utf-8")
    return stamp


def create_isolated_venv(
    base_python_cmd: list[str], venv_dir: Path, log_func=None
) -> list[str]:
    """
    Create an isolated venv at `venv_dir` using the user-selected Python, and
    return the python command for that venv. The caller then installs only
    requirements.txt + pyinstaller into it -> guaranteed lean build.
    """
    venv_dir = Path(venv_dir)
    venv_dir.parent.mkdir(parents=True, exist_ok=True)
    code = run_command(
        base_python_cmd + ["-m", "venv", str(venv_dir)],
        log_func=log_func,
    )
    if code != 0:
        raise RuntimeError(f"Could not create isolated venv at {venv_dir} (exit {code}).")

    if sys.platform.startswith("win"):
        iso_python = venv_dir / "Scripts" / "python.exe"
    else:
        iso_python = venv_dir / "bin" / "python"
    if not iso_python.exists():
        raise RuntimeError(f"Isolated venv created but python not found at {iso_python}.")
    return [str(iso_python)]


# -----------------------------
# Image conversion logic
# -----------------------------
def ensure_pillow(python_cmd: list[str] | None = None, log_func=None) -> None:
    try:
        from PIL import Image  # noqa: F401
        return
    except Exception:
        pass

    if python_cmd is None:
        python_cmd = [sys.executable]

    if log_func:
        log_func("Pillow is not installed. Installing Pillow...")

    run_command(python_cmd + ["-m", "pip", "install", "--upgrade", "pillow"], log_func=log_func)

    from PIL import Image  # noqa: F401


def has_useful_alpha(img) -> bool:
    if img.mode not in ("RGBA", "LA"):
        return False
    alpha = img.getchannel("A")
    extrema = alpha.getextrema()
    return extrema[0] < 255


def auto_remove_border_background(img, mode="light"):
    """
    Flood-fill transparent only the background connected to the image borders.

    mode="light" removes near-white/light neutral border backgrounds.
    mode="dark" removes near-black/dark neutral border backgrounds.

    Border-connected only: it does not remove every black/white pixel inside the icon.
    """
    img = img.convert("RGBA")
    pix = img.load()
    w, h = img.size

    def is_background(pixel):
        r, g, b, a = pixel
        if a < 10:
            return True

        mx = max(r, g, b)
        mn = min(r, g, b)
        spread = mx - mn

        if mode == "dark":
            return mx <= 38 and spread <= 22

        return mx >= 220 and spread <= 24

    visited = set()
    q = deque()

    for x in range(w):
        for y in (0, h - 1):
            if (x, y) not in visited and is_background(pix[x, y]):
                visited.add((x, y))
                q.append((x, y))

    for y in range(h):
        for x in (0, w - 1):
            if (x, y) not in visited and is_background(pix[x, y]):
                visited.add((x, y))
                q.append((x, y))

    while q:
        x, y = q.popleft()
        r, g, b, a = pix[x, y]
        pix[x, y] = (r, g, b, 0)

        for nx, ny in ((x - 1, y), (x + 1, y), (x, y - 1), (x, y + 1)):
            if 0 <= nx < w and 0 <= ny < h and (nx, ny) not in visited:
                if is_background(pix[nx, ny]):
                    visited.add((nx, ny))
                    q.append((nx, ny))

    return img


def auto_remove_light_border_background(img):
    return auto_remove_border_background(img, mode="light")


def auto_remove_dark_border_background(img):
    return auto_remove_border_background(img, mode="dark")


def write_ico_bytes_safely(path: Path, data: bytes, log_func=None) -> None:
    """
    Write ICO bytes via a temporary file, then replace the final file.

    This avoids the Windows/Pillow direct-save issue we hit before, while not
    changing the Python-to-EXE build logic at all.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.parent / f".{path.name}.tmp_write"

    if tmp.exists():
        try:
            tmp.unlink()
        except Exception:
            pass

    if log_func:
        log_func(f"Writing temp ICO: {tmp}")

    with open(str(tmp), "wb") as f:
        f.write(data)

    if log_func:
        log_func(f"Replacing final ICO: {path}")

    try:
        os.replace(str(tmp), str(path))
    except Exception:
        if path.exists():
            try:
                path.unlink()
            except Exception:
                pass
        shutil.move(str(tmp), str(path))


def crop_and_square(img, padding_ratio=0.08):
    from PIL import Image

    img = img.convert("RGBA")
    alpha = img.getchannel("A")
    bbox = alpha.getbbox()

    if bbox:
        left, top, right, bottom = bbox
        bw = right - left
        bh = bottom - top
        pad = int(max(bw, bh) * padding_ratio)

        left = max(0, left - pad)
        top = max(0, top - pad)
        right = min(img.width, right + pad)
        bottom = min(img.height, bottom + pad)

        img = img.crop((left, top, right, bottom))

    side = max(img.width, img.height)
    canvas = Image.new("RGBA", (side, side), (0, 0, 0, 0))
    canvas.paste(img, ((side - img.width) // 2, (side - img.height) // 2), img)
    return canvas


def convert_png_to_ico(
    input_png: Path,
    output_ico: Path,
    remove_light_border=True,
    remove_dark_border=False,
    crop_square=True,
    padding_ratio=0.08,
    python_cmd: list[str] | None = None,
    log_func=None,
) -> Path:
    ensure_pillow(python_cmd=python_cmd, log_func=log_func)
    from PIL import Image

    input_png = normalize_user_path(input_png)
    output_ico = normalize_user_path(output_ico)

    if input_png.suffix.lower() != ".png":
        raise ValueError("Input image must be a .png file.")

    if not input_png.exists():
        raise FileNotFoundError(f"PNG not found: {input_png}")

    output_ico.parent.mkdir(parents=True, exist_ok=True)

    if log_func:
        log_func(f"Input PNG: {input_png}")
        log_func(f"Output ICO: {output_ico}")

    img_original = Image.open(str(input_png))

    if has_useful_alpha(img_original):
        if log_func:
            log_func("Detected real transparency. Preserving alpha.")
        img = img_original.convert("RGBA")
    else:
        img = img_original.convert("RGBA")
        removed_any = False

        if remove_light_border:
            if log_func:
                log_func("No useful transparency detected. Removing light/white/checkerboard border background.")
            img = auto_remove_light_border_background(img)
            removed_any = True

        if remove_dark_border:
            if log_func:
                log_func("Removing dark/black border background. Conservative border-connected removal only.")
            img = auto_remove_dark_border_background(img)
            removed_any = True

        if not removed_any and log_func:
            log_func("No useful transparency detected. Keeping original background.")

    if crop_square:
        if log_func:
            log_func(f"Cropping visible area and making square canvas. Padding: {padding_ratio:.2f}")
        img = crop_and_square(img, padding_ratio=padding_ratio)

    sizes = [(16, 16), (24, 24), (32, 32), (48, 48), (64, 64), (128, 128), (256, 256)]

    buffer = BytesIO()
    img.save(buffer, format="ICO", sizes=sizes)
    write_ico_bytes_safely(output_ico, buffer.getvalue(), log_func=log_func)

    if log_func:
        log_func("ICO created successfully.")

    return output_ico


# -----------------------------
# Subprocess helper
# -----------------------------
def windows_no_console_kwargs() -> dict:
    """
    Hide console windows for subprocesses launched by THIS TOOLBOX.

    This affects:
    - pip install
    - PyInstaller build
    - Test Python
    - python_has_module checks

    This does NOT inject anything into the EXE being built.
    It does NOT add runtime hooks.
    It does NOT patch the target app.
    """
    if not sys.platform.startswith("win"):
        return {}

    kwargs = {
        "creationflags": getattr(subprocess, "CREATE_NO_WINDOW", 0),
    }

    try:
        startupinfo = subprocess.STARTUPINFO()
        startupinfo.dwFlags |= subprocess.STARTF_USESHOWWINDOW
        startupinfo.wShowWindow = 0
        kwargs["startupinfo"] = startupinfo
    except Exception:
        pass

    return kwargs


def run_command(cmd: list[str], cwd: Path | None = None, log_func=None) -> int:
    if log_func:
        log_func("")
        log_func("Running:")
        log_func(" ".join(f'"{c}"' if " " in str(c) else str(c) for c in cmd))
        log_func("")

    process = subprocess.Popen(
        cmd,
        cwd=str(cwd) if cwd else None,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        encoding="utf-8",
        errors="replace",
        bufsize=1,
        **windows_no_console_kwargs(),
    )

    assert process.stdout is not None
    for line in process.stdout:
        if log_func:
            log_func(line.rstrip())

    return process.wait()


def generate_paddleocr_official_args(python_cmd: list[str]) -> tuple[list[str], str]:
    """
    Generate PaddleOCR packaging arguments using PaddleOCR's official packaging logic.

    Official idea:
      pyinstaller app.py --collect-data paddlex --collect-binaries paddle
      plus --copy-metadata for installed packages that PaddleX checks at runtime.
    """
    script = """
import importlib.metadata
try:
    import paddlex
except Exception as exc:
    raise SystemExit(f"Could not import paddlex: {type(exc).__name__}: {exc}")

deps_all = set(paddlex.utils.deps.BASE_DEP_SPECS.keys())
user_deps = []
for dist in importlib.metadata.distributions():
    name = dist.metadata.get("Name")
    if name:
        user_deps.append(name)

deps_need = []
seen = set()
for dep in user_deps:
    if dep in deps_all and dep.lower() not in seen:
        deps_need.append(dep)
        seen.add(dep.lower())

for dep in ["paddleocr", "paddlepaddle", "paddlex"]:
    if dep.lower() not in seen:
        deps_need.append(dep)
        seen.add(dep.lower())

args = ["--collect-data", "paddlex", "--collect-binaries", "paddle"]
for dep in deps_need:
    args.extend(["--copy-metadata", dep])

print(" ".join(args))
"""
    result = subprocess.run(
        python_cmd + ["-c", script],
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        encoding="utf-8",
        errors="replace",
        check=False,
        **windows_no_console_kwargs(),
    )
    output = (result.stdout or "").strip()
    if result.returncode != 0:
        raise RuntimeError(output or f"PaddleOCR args generation failed with exit code {result.returncode}")

    return split_extra_args(output), output


def python_has_module(python_cmd: list[str], module_name: str) -> bool:
    try:
        result = subprocess.run(
            python_cmd + ["-c", f"import {module_name}"],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            check=False,
            **windows_no_console_kwargs(),
        )
        return result.returncode == 0
    except Exception:
        return False


# -----------------------------
# Workers
# -----------------------------
class ConvertWorker(QThread):
    log = pyqtSignal(str)
    finished_ok = pyqtSignal(str)
    failed = pyqtSignal(str)

    def __init__(self, input_png, output_ico, remove_light_border, remove_dark_border, crop_square, padding_ratio, python_cmd):
        super().__init__()
        self.input_png = Path(input_png)
        self.output_ico = Path(output_ico)
        self.remove_light_border = remove_light_border
        self.remove_dark_border = remove_dark_border
        self.crop_square = crop_square
        self.padding_ratio = padding_ratio
        self.python_cmd = python_cmd

    def run(self):
        try:
            convert_png_to_ico(
                self.input_png,
                self.output_ico,
                remove_light_border=self.remove_light_border,
                remove_dark_border=self.remove_dark_border,
                crop_square=self.crop_square,
                padding_ratio=self.padding_ratio,
                python_cmd=self.python_cmd,
                log_func=self.log.emit,
            )
            self.finished_ok.emit(str(self.output_ico))
        except Exception as exc:
            self.failed.emit(str(exc))


class BuildWorker(QThread):
    log = pyqtSignal(str)
    finished_ok = pyqtSignal(str)
    failed = pyqtSignal(str)

    def __init__(
        self,
        python_cmd,
        target_py,
        icon_path,
        output_dir,
        exe_name,
        windowed,
        onefile,
        clean,
        install_pyinstaller,
        install_requirements,
        requirements_path,
        extra_pyinstaller_args,
        data_entries,
        hidden_imports,
        appid_hook_enabled,
        app_user_model_id,
        pyqt_icon_hook_enabled,
        embed_build_stamp,
        isolated_build,
        png_remove_light_border,
        png_remove_dark_border,
        png_crop_square,
        png_padding,
    ):
        super().__init__()
        self.python_cmd = python_cmd
        self.target_py = Path(target_py)
        self.icon_path = Path(icon_path) if icon_path else None
        self.output_dir = Path(output_dir)
        self.exe_name = exe_name.strip()
        self.windowed = windowed
        self.onefile = onefile
        self.clean = clean
        self.install_pyinstaller = install_pyinstaller
        self.install_requirements = install_requirements
        self.requirements_path = Path(requirements_path) if requirements_path else None
        self.extra_pyinstaller_args = list(extra_pyinstaller_args or [])
        self.data_entries = [e for e in (data_entries or []) if str(e).strip()]
        self.hidden_imports = list(hidden_imports or [])
        self.appid_hook_enabled = bool(appid_hook_enabled)
        self.app_user_model_id = str(app_user_model_id or "").strip()
        self.pyqt_icon_hook_enabled = bool(pyqt_icon_hook_enabled)
        self.embed_build_stamp = bool(embed_build_stamp)
        self.isolated_build = bool(isolated_build)
        self.png_remove_light_border = png_remove_light_border
        self.png_remove_dark_border = png_remove_dark_border
        self.png_crop_square = png_crop_square
        self.png_padding = png_padding

    def run(self):
        try:
            self._run_build()
        except Exception as exc:
            self.failed.emit(str(exc))

    def _run_build(self):
        if not self.python_cmd:
            raise ValueError("Python command is empty.")

        if not self.target_py.exists():
            raise FileNotFoundError(f"Python file not found: {self.target_py}")

        if self.target_py.suffix.lower() != ".py":
            raise ValueError("Target file must be a .py file.")

        if not self.exe_name:
            self.exe_name = self.target_py.stem

        self.output_dir.mkdir(parents=True, exist_ok=True)

        self.log.emit(f"Target Python file: {self.target_py}")
        self.log.emit(f"Output folder: {self.output_dir}")
        self.log.emit(f"EXE name: {self.exe_name}")
        self.log.emit("")

        # V1.8: provenance, log a short fingerprint of the source we are about
        # to build. Cheap insurance against "stale binary" misdiagnoses.
        try:
            st = self.target_py.stat()
            self.log.emit(f"Source size:   {st.st_size} bytes")
            self.log.emit(f"Source mtime:  {format_iso(st.st_mtime)}")
            self.log.emit(f"Source sha256: {sha256_file(self.target_py)}")
            self.log.emit("")
        except Exception as exc:
            self.log.emit(f"(could not compute source provenance: {exc})")
            self.log.emit("")

        # Resolve requirements path early, both flows use it.
        # V1.6 supports a custom requirements file. Blank falls back to
        # requirements.txt beside the selected target .py.
        requirements = (
            self.requirements_path if self.requirements_path
            else (self.target_py.parent / "requirements.txt")
        )
        has_requirements = bool(requirements and requirements.exists())

        # Single temp root: iso venv, runtime hooks, build stamp, spec/work all
        # live under it and are cleaned up together below.
        temp_root = Path(tempfile.mkdtemp(prefix="exe_toolbox_pyinstaller_"))
        workpath = temp_root / "work"
        specpath = temp_root / "spec"

        try:
            # V1.8: isolated build, throwaway venv installed from
            # requirements.txt only. Eliminates fat-shared-venv bloat where
            # transitive optional imports drag numpy/pandas/etc. into the EXE.
            if self.isolated_build:
                if not has_requirements:
                    raise RuntimeError(
                        "Isolated build needs a valid requirements.txt. Set one "
                        "explicitly, or place a requirements.txt beside the target .py."
                    )
                self.log.emit("Isolated build: creating clean venv (deps come only from requirements.txt)")
                self.python_cmd = create_isolated_venv(
                    self.python_cmd, temp_root / "iso_venv", log_func=self.log.emit
                )
                run_command(
                    self.python_cmd + ["-m", "pip", "install", "--upgrade", "pip"],
                    log_func=self.log.emit,
                )
                code = run_command(
                    self.python_cmd + ["-m", "pip", "install", "-r", str(requirements), "pyinstaller"],
                    cwd=self.target_py.parent,
                    log_func=self.log.emit,
                )
                if code != 0:
                    raise RuntimeError(f"Isolated venv install failed with exit code {code}.")
                self.log.emit("Isolated venv ready.")
                self.log.emit("")
            else:
                # Normal flow: install reqs on the user's selected Python.
                if self.install_requirements and has_requirements:
                    self.log.emit(f"Requirements file found: {requirements}")
                    code = run_command(
                        self.python_cmd + ["-m", "pip", "install", "-r", str(requirements), "pyinstaller"],
                        cwd=self.target_py.parent,
                        log_func=self.log.emit,
                    )
                    if code != 0:
                        raise RuntimeError(f"Requirements install failed with exit code {code}.")
                elif self.install_requirements:
                    self.log.emit(f"No requirements file found: {requirements}")

                if not python_has_module(self.python_cmd, "PyInstaller"):
                    if self.install_pyinstaller:
                        self.log.emit("PyInstaller is not installed for the selected Python. Installing it...")
                        code = run_command(
                            self.python_cmd + ["-m", "pip", "install", "--upgrade", "pyinstaller"],
                            cwd=self.target_py.parent,
                            log_func=self.log.emit,
                        )
                        if code != 0:
                            raise RuntimeError(f"PyInstaller install failed with exit code {code}.")
                    else:
                        raise RuntimeError("PyInstaller is not installed. Enable 'Install PyInstaller if missing'.")

                # V1.8: fat-venv warning. Only meaningful for the normal flow;
                # the isolated venv is lean by construction.
                bloat = heavy_libs_not_in_requirements(
                    self.python_cmd, requirements if has_requirements else None
                )
                if bloat:
                    self.log.emit("")
                    self.log.emit("WARNING: build interpreter has heavy libraries NOT in requirements.txt:")
                    for lib in bloat:
                        self.log.emit(f"  - {lib}")
                    self.log.emit("Transitive optional imports can drag these into the EXE and bloat it.")
                    self.log.emit("Enable 'Isolated build (lean venv from requirements.txt)' for a smaller exe.")
                    self.log.emit("")

            # Prepare icon.
            final_icon = None
            if self.icon_path:
                if not self.icon_path.exists():
                    raise FileNotFoundError(f"Icon file not found: {self.icon_path}")

                suffix = self.icon_path.suffix.lower()

                if suffix == ".ico":
                    final_icon = self.icon_path
                    self.log.emit(f"Using ICO icon: {final_icon}")
                elif suffix == ".png":
                    final_icon = self.icon_path.with_suffix(".ico")
                    self.log.emit("Icon is a PNG. Converting it to ICO first...")
                    convert_png_to_ico(
                        self.icon_path,
                        final_icon,
                        remove_light_border=self.png_remove_light_border,
                        remove_dark_border=self.png_remove_dark_border,
                        crop_square=self.png_crop_square,
                        padding_ratio=self.png_padding,
                        python_cmd=self.python_cmd,
                        log_func=self.log.emit,
                    )
                    self.log.emit(f"Using converted ICO icon: {final_icon}")
                else:
                    raise ValueError("Icon must be .ico or .png.")

            # Remove old EXE if possible.
            output_exe = self.output_dir / f"{self.exe_name}.exe"
            if output_exe.exists():
                try:
                    output_exe.unlink()
                    self.log.emit(f"Deleted old EXE: {output_exe}")
                except Exception as exc:
                    raise RuntimeError(
                        f"Could not delete old EXE. Is it still running?\n{output_exe}\n\n{exc}"
                    )

            runtime_hook_paths = []
            if self.appid_hook_enabled:
                app_id = self.app_user_model_id or default_app_user_model_id(self.exe_name)
                appid_runtime_hook_path = write_appid_runtime_hook(
                    temp_root / "runtime_hooks" / "set_appusermodelid.py",
                    app_id,
                )
                runtime_hook_paths.append(appid_runtime_hook_path)
                self.log.emit(f"Windows AppUserModelID runtime hook enabled: {app_id}")

            if self.pyqt_icon_hook_enabled:
                if final_icon:
                    pyqt_icon_runtime_hook_path = write_pyqt_icon_runtime_hook(
                        temp_root / "runtime_hooks" / "force_pyqt_window_icon.py",
                        final_icon.name,
                    )
                    runtime_hook_paths.append(pyqt_icon_runtime_hook_path)
                    self.log.emit(f"PyQt runtime window/taskbar icon hook enabled: {final_icon.name}")
                else:
                    self.log.emit("PyQt runtime icon hook requested, but no icon was selected; skipping it.")

            cmd = self.python_cmd + [
                "-m",
                "PyInstaller",
                "--noconfirm",
                "--name",
                self.exe_name,
                "--distpath",
                str(self.output_dir),
                "--workpath",
                str(workpath),
                "--specpath",
                str(specpath),
            ]

            if self.clean:
                cmd.append("--clean")

            if self.onefile:
                cmd.append("--onefile")
            else:
                cmd.append("--onedir")

            if self.windowed:
                cmd.append("--windowed")
            else:
                cmd.append("--console")

            if final_icon:
                cmd.extend(["--icon", str(final_icon)])

                # V1.5:
                # --icon embeds the Windows shell/taskbar/Explorer icon.
                # --add-data bundles the same .ico file inside the EXE so PyQt apps
                # can load it at runtime for the top-left window icon via sys._MEIPASS.
                add_data_arg = pyinstaller_add_data_arg(final_icon, ".")
                cmd.extend(["--add-data", add_data_arg])
                self.log.emit(f"Bundling icon for runtime window icon: {add_data_arg}")

            # V1.7: bundle declared non-Python data files/folders.
            # PyInstaller only auto-collects imported modules, so Flask/Jinja
            # templates/, static/, .env, etc. must be passed via --add-data with
            # the OS-correct separator. Missing these is the classic packaged
            # Flask "Internal Server Error" (template not found -> HTTP 500).
            if self.data_entries:
                self.log.emit("")
                self.log.emit("Bundling extra data files/folders:")
                for raw in self.data_entries:
                    resolved = resolve_data_entry(raw, self.target_py.parent)
                    if resolved is None:
                        continue
                    src, dest = resolved
                    add_data_arg = pyinstaller_add_data_arg(src, dest)
                    cmd.extend(["--add-data", add_data_arg])
                    self.log.emit(f"  --add-data {add_data_arg}")

            # V1.7: hidden imports PyInstaller cannot statically discover
            # (e.g. pystray._win32, the dynamically imported Windows tray backend).
            if self.hidden_imports:
                self.log.emit("")
                self.log.emit("Hidden imports:")
                for mod in self.hidden_imports:
                    cmd.extend(["--hidden-import", mod])
                    self.log.emit(f"  --hidden-import {mod}")

            # V1.8: embed EXE_TOOLBOX_BUILD.json so "which source produced this
            # exe?" is a one-second sha256 check instead of a multi-hour
            # misdiagnosis. Bundled at the EXE root.
            if self.embed_build_stamp:
                stamp_path = temp_root / "stamp" / BUILD_STAMP_FILENAME
                stamp = write_build_stamp(
                    stamp_path,
                    self.target_py,
                    self.exe_name,
                    self.python_cmd,
                    self.isolated_build,
                )
                cmd.extend(["--add-data", pyinstaller_add_data_arg(stamp_path, ".")])
                self.log.emit("")
                self.log.emit(f"Embedded build stamp: {BUILD_STAMP_FILENAME}")
                self.log.emit(f"  source_sha256: {stamp['source_sha256']}")
                self.log.emit(f"  built_at:      {stamp['built_at']}")
                self.log.emit(f"  pyinstaller:   {stamp['pyinstaller_version'] or '?'}")

            for runtime_hook_path in runtime_hook_paths:
                cmd.extend(["--runtime-hook", str(runtime_hook_path)])
                self.log.emit(f"Adding runtime hook: {runtime_hook_path}")

            if self.extra_pyinstaller_args:
                self.log.emit("")
                self.log.emit("Extra PyInstaller arguments:")
                self.log.emit(" ".join(self.extra_pyinstaller_args))
                cmd.extend(self.extra_pyinstaller_args)

            cmd.append(str(self.target_py))

            code = run_command(cmd, cwd=self.target_py.parent, log_func=self.log.emit)
            if code != 0:
                raise RuntimeError(f"PyInstaller failed with exit code {code}.")

            if output_exe.exists():
                self.log.emit("")
                self.log.emit("Build finished successfully.")
                self.log.emit(f"Created: {output_exe}")
                self.log.emit("")
                self.log.emit("If Windows Explorer still shows an old icon, that is usually icon cache.")
                self.log.emit("Try renaming the EXE, refreshing Explorer, or restarting Explorer.")
                self.finished_ok.emit(str(output_exe))
                return

            # In onedir mode, exe may be under dist/name/name.exe.
            onedir_exe = self.output_dir / self.exe_name / f"{self.exe_name}.exe"
            if onedir_exe.exists():
                self.log.emit("")
                self.log.emit("Build finished successfully.")
                self.log.emit(f"Created: {onedir_exe}")
                self.finished_ok.emit(str(onedir_exe))
                return

            raise RuntimeError("PyInstaller finished, but the expected EXE was not found.")

        finally:
            shutil.rmtree(temp_root, ignore_errors=True)


# -----------------------------
# GUI helpers
# -----------------------------
class DropLineEdit(QLineEdit):
    path_dropped = pyqtSignal(str)

    def __init__(self, suffixes=None):
        super().__init__()
        self.suffixes = [s.lower() for s in (suffixes or [])]
        self.setAcceptDrops(True)

    def dragEnterEvent(self, event: QDragEnterEvent):
        if event.mimeData().hasUrls():
            for url in event.mimeData().urls():
                path = Path(url.toLocalFile())
                if not self.suffixes or path.suffix.lower() in self.suffixes:
                    event.acceptProposedAction()
                    return
        event.ignore()

    def dropEvent(self, event: QDropEvent):
        for url in event.mimeData().urls():
            path = Path(url.toLocalFile())
            if not self.suffixes or path.suffix.lower() in self.suffixes:
                self.setText(str(path))
                self.path_dropped.emit(str(path))
                event.acceptProposedAction()
                return
        event.ignore()


class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()

        self.setWindowTitle(f"{APP_NAME} v{APP_VERSION}")
        self.resize(1050, 760)

        self.app_dir = get_app_dir()
        self.current_worker = None

        central = QWidget()
        self.setCentralWidget(central)

        root = QVBoxLayout(central)

        header = QLabel(f"<b>{APP_NAME} v{APP_VERSION}</b>, PNG -> ICO and Python -> EXE builder")
        root.addWidget(header)

        self.tabs = QTabWidget()
        root.addWidget(self.tabs, stretch=1)

        self.log_box = QPlainTextEdit()
        self.log_box.setReadOnly(True)
        self.log_box.setMinimumHeight(170)
        root.addWidget(self.log_box)

        self._build_build_tab()
        self._build_convert_tab()

        self.log(f"App folder: {self.app_dir}")
        self.log("Tip: Drag/drop .png, .ico, or .py files into path boxes.")

    # ---------- common ----------
    def log(self, text: str):
        self.log_box.appendPlainText(str(text))
        cursor = self.log_box.textCursor()
        cursor.movePosition(QTextCursor.MoveOperation.End)
        self.log_box.setTextCursor(cursor)

    def clear_log(self):
        self.log_box.clear()

    def pick_file(self, line_edit: QLineEdit, title: str, file_filter: str):
        path, _ = QFileDialog.getOpenFileName(self, title, line_edit.text() or str(self.app_dir), file_filter)
        if path:
            line_edit.setText(path)

    def pick_save_file(self, line_edit: QLineEdit, title: str, file_filter: str, default_path: str = ""):
        start = line_edit.text() or default_path or str(self.app_dir)
        path, _ = QFileDialog.getSaveFileName(self, title, start, file_filter)
        if path:
            line_edit.setText(path)

    def pick_folder(self, line_edit: QLineEdit, title: str):
        path = QFileDialog.getExistingDirectory(self, title, line_edit.text() or str(self.app_dir))
        if path:
            line_edit.setText(path)

    def python_cmd(self) -> list[str]:
        return split_command(self.python_line.text())

    # ---------- PNG tab ----------
    def _build_convert_tab(self):
        tab = QWidget()
        self.tabs.addTab(tab, "PNG -> ICO")

        layout = QVBoxLayout(tab)

        form_box = QGroupBox("Convert PNG image to Windows ICO")
        layout.addWidget(form_box)

        grid = QGridLayout(form_box)

        self.png_input = DropLineEdit([".png"])
        self.png_input.setPlaceholderText("Select or drag/drop a .png file")
        self.png_input.path_dropped.connect(self._auto_set_ico_output)

        btn_png = QPushButton("Browse PNG")
        btn_png.clicked.connect(lambda: self.pick_file(self.png_input, "Select PNG", "PNG images (*.png);;All files (*.*)"))

        self.ico_output = QLineEdit()
        self.ico_output.setPlaceholderText("Output .ico path")

        btn_ico = QPushButton("Save ICO As")
        btn_ico.clicked.connect(lambda: self.pick_save_file(self.ico_output, "Save ICO", "Icon files (*.ico);;All files (*.*)"))

        grid.addWidget(QLabel("Input PNG:"), 0, 0)
        grid.addWidget(self.png_input, 0, 1)
        grid.addWidget(btn_png, 0, 2)

        grid.addWidget(QLabel("Output ICO:"), 1, 0)
        grid.addWidget(self.ico_output, 1, 1)
        grid.addWidget(btn_ico, 1, 2)

        self.remove_light_cb = QCheckBox("Auto-remove light/white/checkerboard border background")
        self.remove_light_cb.setChecked(True)

        self.remove_dark_cb = QCheckBox("Auto-remove dark/black border background")
        self.remove_dark_cb.setChecked(False)
        self.remove_dark_cb.setToolTip(
            "Optional. Use only when the black area is just the exported canvas/background."
        )

        self.crop_square_cb = QCheckBox("Crop visible image and center it on square canvas")
        self.crop_square_cb.setChecked(True)

        self.padding_spin = QDoubleSpinBox()
        self.padding_spin.setRange(0.0, 0.50)
        self.padding_spin.setSingleStep(0.01)
        self.padding_spin.setValue(0.08)

        grid.addWidget(self.remove_light_cb, 2, 1, 1, 2)
        grid.addWidget(self.remove_dark_cb, 3, 1, 1, 2)
        grid.addWidget(self.crop_square_cb, 4, 1, 1, 2)
        grid.addWidget(QLabel("Padding ratio:"), 5, 0)
        grid.addWidget(self.padding_spin, 5, 1)

        button_row = QHBoxLayout()
        layout.addLayout(button_row)

        convert_btn = QPushButton("Convert PNG -> ICO")
        convert_btn.clicked.connect(self.convert_png_clicked)

        open_folder_btn = QPushButton("Open output folder")
        open_folder_btn.clicked.connect(self.open_ico_output_folder)

        button_row.addWidget(convert_btn)
        button_row.addWidget(open_folder_btn)
        button_row.addStretch()

        info = QLabel(
            "This replaces png_to_ico_converter_V4.bat. It uses Pillow directly and creates a multi-size ICO "
            "with 16, 24, 32, 48, 64, 128, and 256 px entries."
        )
        info.setWordWrap(True)
        layout.addWidget(info)
        layout.addStretch()

    def _auto_set_ico_output(self, path_text: str):
        path = Path(path_text)
        if path.suffix.lower() == ".png":
            self.ico_output.setText(str(path.with_suffix(".ico")))

    def convert_png_clicked(self):
        input_png = normalize_user_path(self.png_input.text())
        output_ico = normalize_user_path(self.ico_output.text()) if self.ico_output.text().strip() else input_png.with_suffix(".ico")

        if not input_png.exists():
            QMessageBox.warning(self, "Missing PNG", "Select a valid PNG file first.")
            return

        self.ico_output.setText(str(output_ico))
        self.clear_log()

        self.current_worker = ConvertWorker(
            input_png=input_png,
            output_ico=output_ico,
            remove_light_border=self.remove_light_cb.isChecked(),
            remove_dark_border=self.remove_dark_cb.isChecked(),
            crop_square=self.crop_square_cb.isChecked(),
            padding_ratio=float(self.padding_spin.value()),
            python_cmd=self.python_cmd(),
        )
        self.current_worker.log.connect(self.log)
        self.current_worker.finished_ok.connect(lambda path: QMessageBox.information(self, "Done", f"Created:\n{path}"))
        self.current_worker.failed.connect(lambda msg: QMessageBox.critical(self, "Conversion failed", msg))
        self.current_worker.finished.connect(lambda: setattr(self, "current_worker", None))
        self.current_worker.start()

    def open_ico_output_folder(self):
        path_text = self.ico_output.text().strip()
        if path_text:
            open_folder(normalize_user_path(path_text).parent)
        else:
            open_folder(self.app_dir)

    # ---------- Build tab ----------
    def _build_build_tab(self):
        """
        V1.9 UI overhaul: the Python -> EXE tab is itself a QTabWidget with four
        focused sub-tabs (Build / Options / Data / Advanced). The common case
        is now: pick .py, click the prominent Build button on the Build sub-tab.
        """
        tab = QWidget()
        self.tabs.addTab(tab, "Python -> EXE")

        layout = QVBoxLayout(tab)

        self.exe_subtabs = QTabWidget()
        layout.addWidget(self.exe_subtabs, stretch=1)

        # Pre-create all widgets so cross-tab connections (textChanged, etc.)
        # can be wired regardless of which sub-tab a widget lives on.
        self._create_build_widgets()

        # Populate sub-tabs.
        self.exe_subtabs.addTab(self._build_subtab_build(), "Build")
        self.exe_subtabs.addTab(self._build_subtab_options(), "Options")
        self.exe_subtabs.addTab(self._build_subtab_data(), "Data && hidden imports")
        self.exe_subtabs.addTab(self._build_subtab_advanced(), "Advanced")

        # Cross-widget signal wiring (after widgets exist).
        self.target_py_line.path_dropped.connect(self._target_py_changed)
        self.exe_name_line.textChanged.connect(self._maybe_update_appid_from_exe_name)
        # AppUserModelID line is only meaningful when the hook is on.
        self.appid_hook_cb.toggled.connect(self.appid_line.setEnabled)
        self.appid_line.setEnabled(self.appid_hook_cb.isChecked())

    # ---------- widget creation (no parenting/layout yet) ----------
    def _create_build_widgets(self):
        # Python interpreter
        self.python_line = QLineEdit(default_python_command())
        self.python_line.setClearButtonEnabled(True)
        self.btn_python = QPushButton("Browse")
        self.btn_python.clicked.connect(
            lambda: self.pick_file(self.python_line, "Select python.exe",
                                   "Python executable (python.exe);;All files (*.*)")
        )
        self.btn_test_python = QPushButton("Test")
        self.btn_test_python.clicked.connect(self.test_python_clicked)

        # Target & output
        self.target_py_line = DropLineEdit([".py"])
        self.target_py_line.setPlaceholderText("Drag/drop the .py file to build, or click Browse")
        self.target_py_line.setClearButtonEnabled(True)
        self.btn_target = QPushButton("Browse")
        self.btn_target.clicked.connect(self.browse_target_py)

        self.requirements_line = DropLineEdit([".txt"])
        self.requirements_line.setPlaceholderText("Optional. Blank = requirements.txt beside the .py")
        self.requirements_line.setClearButtonEnabled(True)
        self.btn_requirements = QPushButton("Browse")
        self.btn_requirements.clicked.connect(
            lambda: self.pick_file(self.requirements_line, "Select requirements file",
                                   "Text files (*.txt);;All files (*.*)")
        )

        self.icon_line = DropLineEdit([".ico", ".png"])
        self.icon_line.setPlaceholderText("Optional. .ico or .png (PNG auto-converted)")
        self.icon_line.setClearButtonEnabled(True)
        self.btn_icon = QPushButton("Browse")
        self.btn_icon.clicked.connect(
            lambda: self.pick_file(self.icon_line, "Select icon",
                                   "Icons/images (*.ico *.png);;All files (*.*)")
        )

        self.output_dir_line = QLineEdit(str(self.app_dir))
        self.output_dir_line.setClearButtonEnabled(True)
        self.btn_outdir = QPushButton("Browse")
        self.btn_outdir.clicked.connect(
            lambda: self.pick_folder(self.output_dir_line, "Select output folder")
        )

        self.exe_name_line = QLineEdit()
        self.exe_name_line.setPlaceholderText("Auto-filled from the .py filename")

        # The prominent action button, sits right under the .py field.
        self.build_btn = QPushButton("⚡  Build EXE")
        self.build_btn.setMinimumHeight(52)
        self.build_btn.setStyleSheet(
            "QPushButton { font-size: 12pt; font-weight: 600; }"
        )
        self.build_btn.clicked.connect(self.build_exe_clicked)

        self.open_out_btn = QPushButton("Open output folder")
        self.open_out_btn.clicked.connect(
            lambda: open_folder(
                normalize_user_path(self.output_dir_line.text())
                if self.output_dir_line.text().strip() else self.app_dir
            )
        )

        # Quick options (visible on Build sub-tab).
        self.windowed_cb = QCheckBox("Windowed (no console)")
        self.windowed_cb.setChecked(True)
        self.onefile_cb = QCheckBox("One-file EXE")
        self.onefile_cb.setChecked(True)
        self.clean_cb = QCheckBox("Clean cache")
        self.clean_cb.setChecked(True)

        # Options sub-tab, build behavior + runtime hooks.
        self.install_pyinstaller_cb = QCheckBox("Install PyInstaller if missing")
        self.install_pyinstaller_cb.setChecked(True)

        self.install_requirements_cb = QCheckBox("Install requirements.txt before building")
        self.install_requirements_cb.setChecked(True)

        self.embed_stamp_cb = QCheckBox("Embed build stamp (EXE_TOOLBOX_BUILD.json)")
        self.embed_stamp_cb.setChecked(True)
        self.embed_stamp_cb.setToolTip(
            "Bundles source sha256, mtime, build time, and toolbox + PyInstaller versions "
            "inside the EXE. Verifies 'is this EXE from the current source?' in seconds."
        )

        self.isolated_build_cb = QCheckBox("Isolated build (lean venv from requirements.txt)")
        self.isolated_build_cb.setChecked(False)
        self.isolated_build_cb.setToolTip(
            "Throwaway venv installed only from your requirements.txt. Avoids dragging heavy "
            "libraries (numpy/pandas/scipy/torch/...) from a fat shared venv into the EXE."
        )

        self.appid_hook_cb = QCheckBox("Windows AppUserModelID runtime hook")
        self.appid_hook_cb.setChecked(True)
        self.appid_hook_cb.setToolTip(
            "Recommended for PyQt apps. Helps Windows show the correct taskbar icon "
            "even when the EXE is not pinned."
        )

        self.appid_line = QLineEdit()
        self.appid_line.setPlaceholderText("Example: Can.MyApp")
        self.appid_line.setToolTip(
            "Stable Windows taskbar identity. Leave the generated value unless you have "
            "a reason to change it."
        )

        self.pyqt_icon_hook_cb = QCheckBox("Force PyQt runtime window/taskbar icon")
        self.pyqt_icon_hook_cb.setChecked(True)
        self.pyqt_icon_hook_cb.setToolTip(
            "Forces QApplication and top-level windows to use the bundled icon at runtime. "
            "Helps when the EXE icon is correct but the unpinned taskbar icon is blank."
        )

        # Data & hidden imports sub-tab.
        self.data_files_edit = QPlainTextEdit()
        self.data_files_edit.setPlaceholderText(
            "templates\n"
            "static\n"
            "icon.png\n"
            ".env | .\n"
            "config\\settings.ini | config"
        )

        self.hidden_imports_line = QLineEdit()
        self.hidden_imports_line.setPlaceholderText(
            "Optional. Comma/space separated, e.g. pystray._win32, win32timezone"
        )

        self.detect_web_btn = QPushButton("Detect web/Flask data")
        self.detect_web_btn.setToolTip(
            "Scans the target .py folder for templates/, static/, icon.png, icon.ico, .env "
            "and adds them. Also adds --collect-data certifi, and pystray._win32 when the "
            "target actually imports pystray."
        )
        self.detect_web_btn.clicked.connect(self.detect_web_app_data)
        self.clear_data_btn = QPushButton("Clear data list")
        self.clear_data_btn.clicked.connect(lambda: self.data_files_edit.setPlainText(""))

        # Advanced sub-tab.
        self.extra_args_edit = QPlainTextEdit()
        self.extra_args_edit.setPlaceholderText(
            "Optional raw PyInstaller args, e.g.:\n"
            "--collect-data paddlex --collect-binaries paddle --copy-metadata ..."
        )
        self.paddleocr_preset_btn = QPushButton("PaddleOCR preset")
        self.paddleocr_preset_btn.clicked.connect(self.use_paddleocr_preset)
        self.clear_extra_args_btn = QPushButton("Clear extra args")
        self.clear_extra_args_btn.clicked.connect(lambda: self.extra_args_edit.setPlainText(""))

    # ---------- sub-tab builders ----------
    def _build_subtab_build(self) -> QWidget:
        page = QWidget()
        v = QVBoxLayout(page)

        # Python interpreter
        py_box = QGroupBox("Python interpreter")
        py_grid = QGridLayout(py_box)
        py_grid.addWidget(QLabel("Python:"), 0, 0)
        py_grid.addWidget(self.python_line, 0, 1)
        py_grid.addWidget(self.btn_python, 0, 2)
        py_grid.addWidget(self.btn_test_python, 0, 3)
        py_grid.setColumnStretch(1, 1)
        v.addWidget(py_box)

        # Build target + the prominent Build button right under .py
        tgt_box = QGroupBox("Build target")
        tgt_grid = QGridLayout(tgt_box)
        tgt_grid.setColumnStretch(1, 1)

        tgt_grid.addWidget(QLabel("Target .py:"), 0, 0)
        tgt_grid.addWidget(self.target_py_line, 0, 1)
        tgt_grid.addWidget(self.btn_target, 0, 2)

        # Build button, spans the full width directly under target .py.
        tgt_grid.addWidget(self.build_btn, 1, 0, 1, 3)

        tgt_grid.addWidget(QLabel("EXE name:"), 2, 0)
        tgt_grid.addWidget(self.exe_name_line, 2, 1, 1, 2)

        tgt_grid.addWidget(QLabel("Output folder:"), 3, 0)
        tgt_grid.addWidget(self.output_dir_line, 3, 1)
        tgt_grid.addWidget(self.btn_outdir, 3, 2)

        tgt_grid.addWidget(QLabel("Icon (.ico/.png):"), 4, 0)
        tgt_grid.addWidget(self.icon_line, 4, 1)
        tgt_grid.addWidget(self.btn_icon, 4, 2)

        tgt_grid.addWidget(QLabel("Requirements:"), 5, 0)
        tgt_grid.addWidget(self.requirements_line, 5, 1)
        tgt_grid.addWidget(self.btn_requirements, 5, 2)
        v.addWidget(tgt_box)

        # Quick options + Open-output button in one compact row.
        quick_box = QGroupBox("Quick options")
        quick_row = QHBoxLayout(quick_box)
        quick_row.addWidget(self.windowed_cb)
        quick_row.addWidget(self.onefile_cb)
        quick_row.addWidget(self.clean_cb)
        quick_row.addStretch(1)
        quick_row.addWidget(self.open_out_btn)
        v.addWidget(quick_box)

        v.addStretch(1)
        return page

    def _build_subtab_options(self) -> QWidget:
        page = QWidget()
        v = QVBoxLayout(page)

        beh_box = QGroupBox("Build behavior")
        beh_v = QVBoxLayout(beh_box)
        beh_v.addWidget(self.install_pyinstaller_cb)
        beh_v.addWidget(self.install_requirements_cb)
        beh_v.addWidget(self.embed_stamp_cb)
        beh_v.addWidget(self.isolated_build_cb)
        v.addWidget(beh_box)

        hook_box = QGroupBox("Runtime hooks (PyQt)")
        hook_grid = QGridLayout(hook_box)
        hook_grid.setColumnStretch(1, 1)
        hook_grid.addWidget(self.appid_hook_cb, 0, 0, 1, 2)
        hook_grid.addWidget(QLabel("    AppUserModelID:"), 1, 0)
        hook_grid.addWidget(self.appid_line, 1, 1)
        hook_grid.addWidget(self.pyqt_icon_hook_cb, 2, 0, 1, 2)
        v.addWidget(hook_box)

        v.addStretch(1)
        return page

    def _build_subtab_data(self) -> QWidget:
        page = QWidget()
        v = QVBoxLayout(page)

        info = QLabel(
            "One data file/folder per line. Relative paths are resolved beside the target .py.\n"
            "Form:  SRC   or   SRC | DEST   (default DEST: folder->its name, file->bundle root)"
        )
        info.setWordWrap(True)
        v.addWidget(info)

        v.addWidget(self.data_files_edit, stretch=1)

        hidden_row = QHBoxLayout()
        hidden_row.addWidget(QLabel("Hidden imports:"))
        hidden_row.addWidget(self.hidden_imports_line, 1)
        v.addLayout(hidden_row)

        btn_row = QHBoxLayout()
        btn_row.addWidget(self.detect_web_btn)
        btn_row.addWidget(self.clear_data_btn)
        btn_row.addStretch(1)
        v.addLayout(btn_row)
        return page

    def _build_subtab_advanced(self) -> QWidget:
        page = QWidget()
        v = QVBoxLayout(page)

        v.addWidget(QLabel("Extra PyInstaller arguments (appended as-is):"))
        v.addWidget(self.extra_args_edit, stretch=1)

        btn_row = QHBoxLayout()
        btn_row.addWidget(self.paddleocr_preset_btn)
        btn_row.addWidget(self.clear_extra_args_btn)
        btn_row.addStretch(1)
        v.addLayout(btn_row)
        return page

    def _maybe_update_appid_from_exe_name(self, exe_name: str):
        """
        Keep the AppUserModelID useful while the user is filling the form.
        If the user manually changes the ID to something custom, do not fight them.
        """
        if not hasattr(self, "appid_line"):
            return

        exe_name = (exe_name or "").strip()
        if not exe_name:
            return

        new_default = default_app_user_model_id(exe_name)
        current = self.appid_line.text().strip()

        if not current or current.startswith("Can."):
            self.appid_line.setText(new_default)

    def use_paddleocr_preset(self):
        cmd = self.python_cmd()
        if not cmd:
            QMessageBox.warning(self, "Missing Python", "Set the Python command first.")
            return

        self.log("Generating PaddleOCR official packaging arguments...")
        try:
            args, text = generate_paddleocr_official_args(cmd)
        except Exception as exc:
            QMessageBox.critical(
                self,
                "PaddleOCR preset failed",
                "Could not generate official PaddleOCR packaging args with the selected Python.\n\n"
                f"{exc}\n\n"
                "Make sure the Python command points to the app venv where paddleocr/paddlex are installed."
            )
            return

        self.extra_args_edit.setPlainText(text)
        self.clean_cb.setChecked(True)
        self.onefile_cb.setChecked(False)

        self.log("PaddleOCR official preset loaded into Extra PyInstaller arguments.")
        self.log("One-file EXE unchecked for safer PaddleOCR onedir testing.")
        self.log(f"Generated {len(args)} extra PyInstaller argument tokens.")

    def detect_web_app_data(self):
        """
        Auto-fill the data list for a typical Flask/web app sitting next to the
        target .py: templates/, static/, common icons, .env. Also wires the
        pystray Windows tray backend (hidden import) and certifi TLS data.
        This directly addresses the packaged-Flask HTTP 500/404 bug report.
        """
        target_text = self.target_py_line.text().strip()
        if not target_text:
            QMessageBox.warning(self, "No target", "Select the target .py first.")
            return

        base = normalize_user_path(target_text)
        base = base.parent if base.suffix.lower() == ".py" else base

        existing = [l.strip() for l in self.data_files_edit.toPlainText().splitlines() if l.strip()]
        found = []

        for folder_name in ("templates", "static"):
            if (base / folder_name).is_dir() and folder_name not in existing:
                found.append(folder_name)

        for file_name in ("icon.png", "icon.ico", "favicon.ico", ".env"):
            entry = f"{file_name} | ."
            if (base / file_name).is_file() and entry not in existing and file_name not in existing:
                found.append(entry)

        if found:
            self.data_files_edit.setPlainText("\n".join(existing + found))

        # V1.8: only wire pystray._win32 when the target actually uses pystray.
        # Adding it unconditionally produced a misleading "Hidden import not
        # found" error for Flask apps that have no tray icon code.
        added_pystray = False
        if target_imports_module(base if base.is_dir() else base.parent, "pystray"):
            hi = self.hidden_imports_line.text().strip()
            if "pystray._win32" not in split_hidden_imports(hi):
                self.hidden_imports_line.setText((hi + " pystray._win32").strip())
                added_pystray = True

        extra = self.extra_args_edit.toPlainText().strip()
        added_certifi = False
        if "--collect-data certifi" not in extra:
            self.extra_args_edit.setPlainText((extra + " --collect-data certifi").strip())
            added_certifi = True

        self.log(f"Web app scan of {base}")
        self.log(f"  Data entries added: {found if found else 'none new (already listed or not present)'}")
        if added_pystray:
            self.log("  Hidden import added: pystray._win32 (target imports pystray)")
        else:
            self.log("  Hidden import pystray._win32: skipped (target does not import pystray)")
        if added_certifi:
            self.log("  Extra arg added: --collect-data certifi")
        if not found:
            self.log("  Note: no templates/, static/, icon.* or .env found beside the .py.")

    def test_python_clicked(self):
        cmd = self.python_cmd()
        if not cmd:
            QMessageBox.warning(self, "Missing Python", "Set the Python command first.")
            return

        self.clear_log()
        self.log("Testing Python command:")
        self.log(" ".join(f'"{c}"' if " " in str(c) else str(c) for c in cmd))
        self.log("")

        try:
            result = subprocess.run(
                cmd + ["--version"],
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
                encoding="utf-8",
                errors="replace",
                check=False,
                **windows_no_console_kwargs(),
            )
            output = (result.stdout or "").strip()
            self.log(output or "(No output)")
            self.log(f"Exit code: {result.returncode}")

            if result.returncode == 0:
                QMessageBox.information(self, "Python OK", output or "Python command works.")
            else:
                QMessageBox.warning(self, "Python returned an error", output or f"Exit code: {result.returncode}")

        except Exception as exc:
            QMessageBox.critical(
                self,
                "Python command failed",
                f"Could not run the Python command:\n\n{self.python_line.text()}\n\n{exc}"
            )

    def browse_target_py(self):
        path, _ = QFileDialog.getOpenFileName(self, "Select Python file", self.target_py_line.text() or str(self.app_dir), "Python files (*.py);;All files (*.*)")
        if path:
            self.target_py_line.setText(path)
            self._target_py_changed(path)

    def _target_py_changed(self, path_text: str):
        path = normalize_user_path(path_text)
        if path.suffix.lower() == ".py":
            self.output_dir_line.setText(str(path.parent))
            self.exe_name_line.setText(path.stem)

            # V1.6: if this app has its own local venv, use it unless the user
            # already manually set a specific Python path.
            local_venv_python = path.parent / ".venv" / "Scripts" / "python.exe"
            current_python = self.python_line.text().strip().lower()
            current_default = default_python_command().strip().lower()
            if local_venv_python.exists() and (
                not current_python
                or current_python in {"py -3", "python"}
                or current_python == current_default
            ):
                self.python_line.setText(str(local_venv_python))

            # V1.6: auto-select requirements.txt beside the app if present.
            requirements = path.parent / "requirements.txt"
            if requirements.exists() and not self.requirements_line.text().strip():
                self.requirements_line.setText(str(requirements))

            # If exactly one ICO exists beside the .py, auto-select it.
            icons = sorted(path.parent.glob("*.ico"))
            if len(icons) == 1 and not self.icon_line.text().strip():
                self.icon_line.setText(str(icons[0]))

            if hasattr(self, "appid_line") and not self.appid_line.text().strip():
                self.appid_line.setText(default_app_user_model_id(path.stem))

    def build_exe_clicked(self):
        target_py = normalize_user_path(self.target_py_line.text())
        if not target_py.exists():
            QMessageBox.warning(self, "Missing target", "Select a valid .py file first.")
            return

        python_cmd = self.python_cmd()
        if not python_cmd:
            QMessageBox.warning(self, "Missing Python", "Set the Python command first.")
            return

        # V1.8: soft-confirm when the chosen .py looks stale (lives in a
        # snapshot folder, or a same-base-name sibling is newer). The
        # StoryTeller misdiagnosis would have surfaced as a confirmation here.
        stale_reason = stale_source_reason(target_py)
        if stale_reason:
            reply = QMessageBox.warning(
                self,
                "Possibly stale source",
                f"{stale_reason}\n\nBuild this file anyway?",
                QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No,
                QMessageBox.StandardButton.No,
            )
            if reply != QMessageBox.StandardButton.Yes:
                return

        exe_name = self.exe_name_line.text().strip() or target_py.stem
        output_dir = normalize_user_path(self.output_dir_line.text()) if self.output_dir_line.text().strip() else target_py.parent
        icon_text = str(normalize_user_path(self.icon_line.text())) if self.icon_line.text().strip() else ""
        requirements_text = str(normalize_user_path(self.requirements_line.text())) if self.requirements_line.text().strip() else ""
        extra_args = split_extra_args(self.extra_args_edit.toPlainText())
        data_entries = [l.strip() for l in self.data_files_edit.toPlainText().splitlines() if l.strip()]
        hidden_imports = split_hidden_imports(self.hidden_imports_line.text())

        self.clear_log()

        self.current_worker = BuildWorker(
            python_cmd=python_cmd,
            target_py=target_py,
            icon_path=icon_text,
            output_dir=output_dir,
            exe_name=exe_name,
            windowed=self.windowed_cb.isChecked(),
            onefile=self.onefile_cb.isChecked(),
            clean=self.clean_cb.isChecked(),
            install_pyinstaller=self.install_pyinstaller_cb.isChecked(),
            install_requirements=self.install_requirements_cb.isChecked(),
            requirements_path=requirements_text,
            extra_pyinstaller_args=extra_args,
            data_entries=data_entries,
            hidden_imports=hidden_imports,
            appid_hook_enabled=self.appid_hook_cb.isChecked(),
            app_user_model_id=self.appid_line.text().strip() or default_app_user_model_id(exe_name),
            pyqt_icon_hook_enabled=self.pyqt_icon_hook_cb.isChecked(),
            embed_build_stamp=self.embed_stamp_cb.isChecked(),
            isolated_build=self.isolated_build_cb.isChecked(),
            png_remove_light_border=self.remove_light_cb.isChecked(),
            png_remove_dark_border=self.remove_dark_cb.isChecked(),
            png_crop_square=self.crop_square_cb.isChecked(),
            png_padding=float(self.padding_spin.value()),
        )
        self.current_worker.log.connect(self.log)
        self.current_worker.finished_ok.connect(lambda path: QMessageBox.information(self, "Build complete", f"Created:\n{path}"))
        self.current_worker.failed.connect(lambda msg: QMessageBox.critical(self, "Build failed", msg))
        self.current_worker.finished.connect(lambda: setattr(self, "current_worker", None))
        self.current_worker.start()


def main():
    set_windows_app_id(default_app_user_model_id(APP_NAME))

    app = QApplication(sys.argv)
    app.setApplicationName(APP_NAME)
    apply_app_icon(app)

    window = MainWindow()
    apply_app_icon(window)
    window.show()

    raise SystemExit(app.exec())


if __name__ == "__main__":
    main()
